### ISSUE TITLE
请问这本书和您深蓝学院的课程有什么区别？

### ISSUE THREAD

**Issue by igeng** [huangjia2019/llm_gpt#1]
咖哥好，关注您很久了，这本书也购买了，正在学习，请问您的这本书和深蓝学院的课程（https://www.shenlanxueyuan.com/course/620）有什么区别，哪个内容涵盖的更多一点？谢谢您！

**Comment by huangjia2019** [comment]
您好您好，这个书和深蓝学院的课程是一致的！！ 只是呈现形式不同。
喜欢看视频才去深蓝学院吧。如果不非要看视频，看书就足够了。

可以加我微信jackyhuang79。谢谢支持！

**Comment by huangjia2019** [comment]
已经回答！
